name: Test with Gradle, Docker Compose, and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: players
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.5'

      - name: Build with Gradle 8.5
        run: gradle build

      # Start the Docker Compose services
      - name: Start Docker Compose
        run: docker-compose -f mybatis-test/docker-compose.yml up -d

      - name: Execute players-data.sql
        run: |
          mysql -h 127.0.0.1 --port 3307 -u root -ppassword players < $(find ./ -name players-data.sql)

      - name: Wait for MySQL to be ready
        run: dockerize -wait tcp://localhost:3307 -timeout 1m

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/players?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: user  # データベースのユーザー名に合わせて修正
          SPRING_DATASOURCE_PASSWORD: password  # データベースのパスワードに合わせて修正
        run: gradle test --info

      # Stop and remove the Docker Compose services
      - name: Stop Docker Compose
        run: docker-compose -f mybatis-test/docker-compose.yml down

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          job_name: 'Test Report'
