name: Run Test with Gradle and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DB_URL: jdbc:mysql://localhost:3307/players
      DB_USERNAME: user
      DB_PASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.5
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: '8.5'

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "Waiting for MySQL to start..."
          timeout 60 bash -c 'until mysql -h localhost -P 3307 -u user -p password -e ";" ; do sleep 5; done'
          echo "MySQL started"

      - name: Test with Gradle
        env:
          DB_URL: jdbc:mysql://localhost:3307/players
          DB_USERNAME: user
          DB_PASSWORD: password
        run: |
          ./gradlew clean test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          job_name: 'Test Report'
